In [16]:
my_file = open('numbers.txt', 'w')
for i in range(4):
    my_file.write(str(input('Enter a number')))
    my_file.write("\n")
my_file.close()

In [26]:
examMark = int(input('Enter your exam mark to be converted to a grade'))
if examMark >= 90 and examMark <= 100:
    print('Your exam grade is an A, thats Excellent')
elif examMark >= 80 and examMark <= 89:
    print('Your exam grade is an B, thats Brillant')
elif examMark >= 70 and examMark <= 79:
    print('Your exam grade is an c, thats great')
elif examMark >= 50 and examMark <= 69:
    print('Your exam grade is an D, you have passed the exam')
else:
    print('You have failed your exam and will need to revise for your exam')

You have failed and will need to revise for your exam


In [9]:
import numpy as np

In [33]:
numbers =np.array([0,1,2,3,4,5,6,7,8,9])
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers[0:10:2])

[1 3 5 7 9]


In [62]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

newArray = array.reshape(2, 5) 
print(newArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [64]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
c = np.dot(a, b)
print(c)

385


In [82]:
a = np.arange(0,9).reshape(3,3)
b = np.arange(1,10).reshape(3,3)
c = np.dot(a, b)
total_sum = np.sum(c)
print(total_sum)
print(c)

594
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
